version: '3.4'

services:

  signature-api:
    container_name: signature-api
    image: signature_plus:prod
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:kdys@mysql:3307/signature_plus?connect_timeout=300
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: prod-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3307
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=kdys
      - MYSQL_DATABASE=signature_plus
    volumes:
      - mysql:/var/lib/mysqlql/data

volumes:
  mysql:
    name: signature-db
